### ISSUE TITLE
Typo with comments

### ISSUE THREAD

**Issue by AngleWyrm10** [battlemage64/Rimbrellas#2]
The following lines contains a '>' character that confuses the parser
https://github.com/battlemage64/Rimbrellas/blob/0c5c2685e409ba1e66c4469ebdcdd5eab6c162cb/About/Manifest.xml#L8
https://github.com/battlemage64/Rimbrellas/blob/0c5c2685e409ba1e66c4469ebdcdd5eab6c162cb/About/Manifest.xml#L15

**Comment by battlemage64** [comment]
Oops! Thank you! I don't know why ModManager didn't catch this for me when I tested it. Should be fixed now.
